Improve talent portal
blindnet-io/dogfood pull request #14
Opened 2022-10-31 14:59 UTC by milstan

- add devkit authentication
- limit to PDF files
- add github profile field

2022-10-31 15:22 UTC, m4rk055 requested changes

2022-10-31 15:22 UTC, m4rk055 commented on common/js/submit.js
>              id: email,
This email value will be ignored, as user id is extracted from the token. Token needs to be generated for the specific email or you can generate an app scoped token (dangerous!) and use [this endpoint](https://devkit-pce-staging.azurewebsites.net/swagger/#/User%20events/postV0User-eventsConsentStore).

2022-10-31 18:03 UTC, milstan commented on common/js/submit.js
>              id: email,
@m4rk055 changed. See if OK now.

2022-10-31 18:29 UTC, m4rk055 commented on common/js/submit.js
> +  return tokenPromise = builder.user(email);
```suggestion
  const tokenPromise = builder.user(email);
  return tokenPromise;
```

2022-10-31 18:29 UTC, m4rk055 commented on common/js/submit.js
> +      registerConsent(token).then((response) => {
```suggestion
      return registerConsent(token).then((response) => {
```

2022-10-31 18:29 UTC, m4rk055 commented on common/js/submit.js
> +  fetch('https://jirxtzamlvwamuyigzmj.supabase.co/rest/v1/cv-sumbissions', {
```suggestion
  return fetch('https://jirxtzamlvwamuyigzmj.supabase.co/rest/v1/cv-sumbissions', {
```

2022-10-31 18:29 UTC, m4rk055 commented on common/js/submit.js
> +          submitData(formData);
```suggestion
          return submitData(formData);
```

2022-11-01 09:25 UTC, milstan commented
changes you requested are in last commit @m4rk055 feelf free to merge if happy with them

2022-11-01 16:04 UTC, milstan commented
@m4rk055 there is an issue - the token is generated, but the consent endpoint returns 401 unauthroised

2022-11-02 09:25 UTC, m4rk055 approved these changes

2022-11-02 09:26 UTC, m4rk055 commented
> @m4rk055 there is an issue - the token is generated, but the consent endpoint returns 401 unauthroised

Fixed

2022-11-02 10:36 UTC, merged